# -*- coding: utf-8 -*-
"""Book Recommender System

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1P8-nr-QmST8Eq-81kHHlXolPbzt8DmVL
"""

# Books Recommender System using clustering | Collaborative based

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

Books = pd.read_csv('/content/Books.csv')

Books.head()

Books.shape

Books.columns

Books = Books[['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-L']]

Books.head()

Books.rename(columns={
    "Book-Title": "Title",
    "Book-Author": "Author",
    "Year-Of-Publication": "Year",
    "Publisher": "Publisher",
    "Image-URL-L": "Img_URL"},inplace = True)

Books.head()

Users = pd.read_csv('/content/Users.csv')

Users.head()

Users.shape

Ratings = pd.read_csv('/content/Ratings.csv')

Ratings.head()

Ratings.shape

print(Books.shape)
print(Users.shape)
print(Ratings.shape)

Ratings.rename(columns={
    "User-ID": "user_id",
    "Book-Rating": "ratings"
}, inplace= True)

Ratings.head()

Ratings['user_id'].value_counts()

Ratings['user_id'].unique().shape

X = Ratings['user_id'].value_counts() > 200

X[X].shape

Y = X[X].index

Y

Ratings= Ratings[Ratings['user_id'].isin(Y)]

Ratings.head()

Ratings.shape

Ratings_with_Books = Ratings.merge(Books, on="ISBN")

Ratings_with_Books.head()

Ratings_with_Books.shape

num_rating = Ratings_with_Books.groupby('Title')['ratings'].count().reset_index()

num_rating.head()

num_rating.rename(columns={"rating:": "num_of_rating"}, inplace=True)

num_rating.head()

final_rating = Ratings_with_Books.merge(num_rating, on= 'Title')

final_rating.head()

final_rating.shape

if 'num_of_rating' in final_rating.columns:
  final_rating = final_rating[final_rating['num_of_rating'] >= 50]

final_rating.sample(10)

final_rating.shape

final_rating.drop_duplicates(['user_id','Title'], inplace=True)

final_rating.shape

final_rating